### ISSUE TITLE
Improve CRD schema

### ISSUE THREAD

**Issue by sarmad-abualkaz** [sarmad-abualkaz/k8s-scheduled-pod-autoscaler#3]
Use a list of scale actions with a newer more concise schema - as per [comments](https://github.com/sarmad-abualkaz/k8s-scheduled-pod-autoscaler/pull/1#discussion_r588718453) from @andrewhertog

```
scheduledEvents:
- name: Event1
  time: 8:00AM
  value: 25
- name: Event2
  time: 6:00PM
  value: 5
....
```
